image: golang:1.15

variables:
  GOFLAGS: -mod=readonly

cache:
  paths:
    - vendor

before_script:
  - apt-get update
  - apt-get install -y
    fuse
    libfuse-dev
  - apt-get clean

stages:
  - dependencies
  - test

.modcache: &modcache
  key: modcache
  paths:
    - vendor/

dependencies:
  stage: dependencies
  script: go mod download
  cache: *modcache

test:
  stage: test
  script: make race
  cache:
    <<: *modcache
    policy: pull
